import Head from 'next/head'
import Image from 'next/image'




export default function Home() {
  return (
    <div >
      <Head>
        <title>EduCare.com - Educational platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>
  
  </div> 
  <section className="text-gray-600 body-font">
  <div className="container px-5 py-24 mx-auto">
    <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
      <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">India's largest learning platform</h1>
      <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">We educate, we care.</p>
    </div>
    <div className="flex flex-wrap -m-4">
      <div className="xl:w-1/3 md:w-1/2 p-4">
        <div className="border border-gray-200 p-6 rounded-lg">
          <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-6 h-6" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <h2 className="text-lg text-gray-900 font-medium title-font mb-2">The complete 2022 webdev bootcamp</h2>
          <p className="leading-relaxed text-base">The Complete 2022 Web Development BootcampBecome a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DAppsRating: 4.7 out of 5205007 reviews65.5 total hours490 lecturesAll LevelsCurrent price: ₹549Original price: ₹3,999</p>
        </div>
      </div>
      <div className="xl:w-1/3 md:w-1/2 p-4">
        <div className="border border-gray-200 p-6 rounded-lg">
          <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-6 h-6" viewBox="0 0 24 24">
              <circle cx="6" cy="6" r="3"></circle>
              <circle cx="6" cy="18" r="3"></circle>
              <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
            </svg>
          </div>
          <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Complete Python pro bootcamp</h2>
          <p className="leading-relaxed text-base">100 Days of Code: The Complete Python Pro Bootcamp for 2022Master Python by building 100 projects in 100 days. Learn data science, automation, build websites, games and apps!Rating: 4.7 out of 5119948 reviews64 total hours676 lecturesAll LevelsCurrent price: ₹549Original price: ₹3,999</p>
        </div>
      </div>
      <div className="xl:w-1/3 md:w-1/2 p-4">
        <div className="border border-gray-200 p-6 rounded-lg">
          <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-6 h-6" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Complete JavaScript course</h2>
          <p className="leading-relaxed text-base">100 Days of Code: The Complete Python Pro Bootcamp for 2022Master Python by building 100 projects in 100 days. Learn data science, automation, build websites, games and apps!Rating: 4.7 out of 5119948 reviews64 total hours676 lecturesAll LevelsCurrent price: ₹549Original price: ₹3,999</p>
        </div>
      </div>
      <div className="xl:w-1/3 md:w-1/2 p-4">
        <div className="border border-gray-200 p-6 rounded-lg">
          <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-6 h-6" viewBox="0 0 24 24">
              <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1zM4 22v-7"></path>
            </svg>
          </div>
          <h2 className="text-lg text-gray-900 font-medium title-font mb-2">React-The complete guide</h2>
          <p className="leading-relaxed text-base">React - The Complete Guide (incl Hooks, React Router, Redux)Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!Rating: 4.6 out of 5154376 reviews48.5 total hours494 lecturesAll LevelsCurrent price: ₹499Original price: ₹3,499</p>
        </div>
      </div>
      <div className="xl:w-1/3 md:w-1/2 p-4">
        <div className="border border-gray-200 p-6 rounded-lg">
          <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-6 h-6" viewBox="0 0 24 24">
              <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"></path>
            </svg>
          </div>
          <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Complete Python bootcamp</h2>
          <p className="leading-relaxed text-base">2022 Complete Python Bootcamp From Zero to Hero in Python
Updated March 2021
22 total hoursAll LevelsSubtitles
Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games</p>
        </div>
      </div>
      <div className="xl:w-1/3 md:w-1/2 p-4">
        <div className="border border-gray-200 p-6 rounded-lg">
          <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-6 h-6" viewBox="0 0 24 24">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
            </svg>
          </div>
          <h2 className="text-lg text-gray-900 font-medium title-font mb-2">Learn SQL+ Security</h2>
          <p className="leading-relaxed text-base">Learn SQL +Security(pen) testing from ScratchStep by step Tutorial to learn SQL and Web Security testing with real time examplesRating: 4.6 out of 52171 reviews13.5 total hours117 lecturesAll LevelsCurrent price: ₹499Original price: ₹3,499</p>
        </div>
      </div>
    </div>
    
  </div>
</section>



</div>
    
  )
}
